#!/bin/bash
clear

RED='\033[0;31m'
BLUE='\033[0;34m'
NC='\033[1;37m'

function inshide(){
wget -qO /usr/local/bin/add-ssh-user https://raw.githubusercontent.com/LawNetwork/Autoscript/main/hidessh/Noobzvpns/add-ssh-user
wget -qO /usr/local/bin/del-ssh-user https://raw.githubusercontent.com/LawNetwork/Autoscript/main/hidessh/Noobzvpns/del-ssh-user
chmod +x /usr/local/bin/add-ssh-user
chmod +x /usr/local/bin/del-ssh-user
plugin
}

function unshide(){
if [ -e "$file_path" ]; then
        rm /usr/local/bin/add-ssh-user
else
        :
fi
plugin
}

function plugin(){
clear
file_path="/usr/local/bin/add-ssh-user"

if [ -e "$file_path" ]; then
    onoff="$NC[${BLUE}ON$NC]  "
else
    onoff="$NC[${RED}OFF$NC] "
fi
echo -e "================================"
echo -e "|         PLUGINS MENU         |"
echo -e "================================"
echo -e "| Status $onoff                |"
echo -e "| ---------------------------- |"
echo -e "| [1] Install Plugins          |"
echo -e "| [2] Uninstall Plugins        |"
echo -e "|                              |"
echo -e "| [0] Back to menu             |"
echo -e "================================"
echo -ne "Choose option: "; read opt1

case $opt1 in
01 | 1) inshide ;;
02 | 2) unshide ;;
00 | 0) clear ; menu ;;
*) clear ; menu ;;
esac
}

service_file="/etc/systemd/system/multi-user.target.wants/noobzvpns.service"

if [ -e "$service_file" ]; then
        service_status="Installed"

        status_output=$(systemctl status noobzvpns)
        if [[ $status_output == *"Active: active (running)"* ]]; then
                noobstat="Service ${BLUE}Online${NC}"
        else
                noobstat="Service ${RED}Offline$NC"
        fi
else
        service_status="Not Installed"
        noobstat=""
fi

function insnoob(){
service_file="/etc/systemd/system/multi-user.target.wants/noobzvpns.service"
if [ -e "$service_file" ]; then
        /root/noobzvpns/./uninstall.sh
else
        /root/noobzvpns/./install.sh
fi
menu
}

function ensnoob(){
status_output=$(systemctl status noobzvpns)
if [[ $status_output == *"Active: active (running)"* ]]; then
        systemctl stop noobzvpns.service
else
        systemctl start noobzvpns.service
fi
menu
}

#====================== Addons =====================
#1 System Uptime
uphours=`uptime -p | awk '{print $2,$3}' | cut -d , -f1`
upminutes=`uptime -p | awk '{print $4,$5}' | cut -d , -f1`
uptimecek=`uptime -p | awk '{print $6,$7}' | cut -d , -f1`
cekup=`uptime -p | grep -ow "day"`
if [ "$cekup" = "day" ]; then
        isdaily="$uphours $upminutes $uptimecek"
else
        isdaily="$uphours $upminutes"
fi

#2 Memory Usage
tram=$(free -m | awk 'NR==2 {print $2}')
uram=$(free -m | awk 'NR==2 {print $3}')
freeram=$(($tram - $uram))

#3 ISP and City
ISP=$(cat /etc/lukman/isp | cut -d " " -f 2-10 )
CITY=$(cat /etc/lukman/city)

#4 Domain
domain=$(cat /etc/lukman/domain)

#5 IP Server
IPVPS=$(cat /etc/lukman/ip)
sensored_ip=$(echo $IPVPS | sed 's/\.[0-9]*\.[0-9]*$/.*.*/')
#=======================================================

function addnoob(){
echo -e "${NC}======================================"
echo -e "|           NOOBZVPNS MENU           |"
echo -e "======================================"
echo -ne "| Username : "; read usernameNew
echo -ne "| Password : "; read passNew
echo -e "======================================"

noobzvpns --add-user $usernameNew $passNew 

echo -e "Created SSH Account Successfully
Username : $usernameNew
Password : $passNew" > /etc/lukman/store/$usernameNew

clear
echo -e "=============================
|         NoobzVPNs         |
=============================
| Username : $usernameNew
| Password : $passNew
============================="
read -n 1 -s -r -p "  Press any key to go back"
menu
}

function delnoob(){
clear
echo -e "${NC}======================================"
echo -e "|           NOOBZVPNS MENU           |"
echo -e "======================================"
noobzvpns --info-all-user | grep '+ ' | awk '{print $2}' | awk 'BEGIN {print "| Nama user:"} {printf "| %d. %s\n", NR, $1}'
echo -e "| -----------------------------------"
echo -e "| Select one you wanna remove"
echo -ne "| Username : "; read usernameNew
echo -e "======================================"

if [ -z "$usernameNew" ]; then
        :
else
noobzvpns --remove-user $usernameNew
rm /etc/lukman/store/$usernameNew
fi
read -n 1 -s -r -p "  Press any key to go back"
menu
}

clear
echo -e "${NC}======================================"
echo -e "|           NOOBZVPNS MENU           |"
echo -e "======================================"
echo -e "| Client Name    : Lukman Priya"
echo -e "| System Uptime  : $isdaily"
echo -e "| Memory Usage   : ${uram}MB / ${tram}MB"
echo -e "| ISP & City     : $ISP & $CITY"
echo -e "| Current Domain : $domain"
echo -e "| IP Server      : $sensored_ip"
echo -e "| Noobz Status   : $service_status"
echo -e "| Service Status : $noobstat"
echo -e "======================================"
echo -e "| [1] Add User                       |"
echo -e "| [2] Delete User                    |"
echo -e "| [3] Plugin Hidessh                 |"
echo -e "|                                    |"
echo -e "| [4] Install/Uninstall Noobz        |"
echo -e "| [5] Enable/Disable Noobz Service   |"
echo -e "| [6] Update Script                  |"
echo -e "|                                    |"
echo -e "| [0] Exit                           |"
echo -e "======================================"
echo -ne "Choose option: "; read opt

#read -n 1 -s -r -p "    Press any key to back on menu"

case $opt in
01 | 1) clear ; addnoob ;;
02 | 2) clear ; delnoob ;;
03 | 3) clear ; plugin ;;
04 | 4) clear ; insnoob ;;
05 | 5) clear ; ensnoob ;;
06 | 6) clear ; wget -qO update raw.githubusercontent.com/LawVPN/Noobz/main/update; bash update; rm update ;;
00 | 0) exit ;;
*) clear ; menu ;;
esac
