#!/bin/bash
clear

echo -e  "Simple profiling for personal use *Leave it blank to skip*"
echo -ne "Enter Domain  : "; read domain
#echo -ne "Enter Chat ID : "; read chat_id
echo -ne "Enter Bot Token : "; read bot_token

apt update; apt install -y vnstat nload htop nethogs curl git
apt upgrade
cd
wget -qO /usr/bin/menu raw.githubusercontent.com/LawVPN/Noobz/main/menu; chmod +x /usr/bin/menu
wget -qO /usr/bin/menu raw.githubusercontent.com/LawVPN/Noobz/main/update; chmod +x /usr/bin/update
git clone https://github.com/noobz-id/noobzvpns.git

clear
mkdir -p /etc/lukman

echo "$domain" > /etc/lukman/domain
#echo "$chat_id" > /etc/lukman/chat_id
echo "$bot_token" > /etc/lukman/bot_token

echo "menu" > /root/.profile

#Addons
echo -e "#!/bin/bash
clear" > /usr/bin/c; chmod +x /usr/bin/c

rm setup
menu
