#!/bin/bash

# February 13th 2024
clear
ip=$(curl ipinfo.io/ip); echo "$ip" > /etc/lukman/ip
city=$(curl ipinfo.io/city); echo "$city" > /etc/lukman/city
org=$(curl ipinfo.io/org); echo "$org" > /etc/lukman/org
isp=$(curl ipinfo.io/org); echo "$isp" > /etc/lukman/isp

# February 15th 2024
wget -qO /usr/bin/menu raw.githubusercontent.com/LawVPN/Noobz/main/menu

menu
